name: "Chain Status Action"
author: "Enrique Mingorance Cano <emingora@redhat.com>"
description: Generates data for chain status webpage

inputs:
  definition-file:
    description: "the file where the build chain is defined. It can a file in the same repository (relative path) or a URL."
    required: true
  title:
    description: "The project title."
    default: "Project Status"
    required: false
  subtitle:
    description: "The project subtitle."
    default: "Contribution status"
    required: false
  output-folder-path:
    description: "the path where the file should be stored"
    required: false
  base-branch-filter:
    description: "A comma separated list of base branches RegEx to be filtered. Like `main,7.59.x,8.x` or `main,^7.*`"
    required: false
  created-by:
    description: "The user/machine/whatever that regenerates the report"
    default: "github action"
    required: false
  created-url:
    description: "Normally the job generating the info URL"
    required: false
  logger-level:
    description: "the log level. 'info' (default) | 'trace' | 'debug'"
    default: "info"
    required: false
runs:
  using: "node16"
  main: "packages/action/dist/index.js"
branding:
  icon: "box"
  color: "red"
