name: "Chain Status Action"
author: "Enrique Mingorance Cano <emingora@redhat.com>"
description: Generates data for chain status webpage

inputs:
  definition-file:
    description: "the file where the build chain is defined. It can a file in the same repository (relative path) or a URL"
    required: true
runs:
  using: "node14"
  main: "packages/action/dist/index.js"
branding:
  icon: "box"
  color: "red"